name: b5_proyek_4
description: "PRASASTI - Pusat Rekam Aktivitas dan Sistem Adminstrasi Terintegrasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Local Database - Offline First
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0

  # HTTP Client
  dio: ^5.0.0

  # Network Detection
  connectivity_plus: ^6.0.0

  # UUID Generator
  uuid: ^4.0.0

  # Charts untuk Dashboard
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.0

  # Code Generation (Hive adapters + Mockito mocks)
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true